Internal Server Error: /number_mac_mem/4
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/main/views.py", line 122, in mac_rub_mem
    mac_name=mac[0].mac_adr
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /portal/redlion
[2020-09-15 08:34:49 +0000] [40477] [INFO] Handling signal: term
[2020-09-15 08:34:49 +0000] [40479] [INFO] Worker exiting (pid: 40479)
[2020-09-15 08:34:49 +0000] [40477] [INFO] Shutting down: Master
[2020-09-15 09:51:24 +0000] [45302] [INFO] Starting gunicorn 20.0.4
[2020-09-15 09:51:24 +0000] [45302] [INFO] Listening at: http://127.0.0.1:8000 (45302)
[2020-09-15 09:51:24 +0000] [45302] [INFO] Using worker: sync
[2020-09-15 09:51:24 +0000] [45304] [INFO] Booting worker with pid: 45304
Internal Server Error: /nkvm
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/myproject/main/views.py", line 26, in nkvm
    k=json.loads(request.body)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /nkvm
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/myproject/main/views.py", line 26, in nkvm
    k=json.loads(request.body)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /nkvm
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/myproject/main/views.py", line 26, in nkvm
    k=json.loads(request.body)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /nkvm
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/myproject/main/views.py", line 26, in nkvm
    k=json.loads(request.body)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-15 09:51:46 +0000] [45302] [INFO] Handling signal: term
[2020-09-15 09:51:46 +0000] [45304] [INFO] Worker exiting (pid: 45304)
[2020-09-15 09:51:46 +0000] [45302] [INFO] Shutting down: Master
[2020-09-15 10:07:56 +0000] [45471] [INFO] Starting gunicorn 20.0.4
[2020-09-15 10:07:56 +0000] [45471] [INFO] Listening at: http://127.0.0.1:8000 (45471)
[2020-09-15 10:07:56 +0000] [45471] [INFO] Using worker: sync
[2020-09-15 10:07:56 +0000] [45473] [INFO] Booting worker with pid: 45473
[2020-09-15 10:09:52 +0000] [45471] [INFO] Handling signal: term
[2020-09-15 10:09:52 +0000] [45473] [INFO] Worker exiting (pid: 45473)
[2020-09-15 10:09:52 +0000] [45471] [INFO] Shutting down: Master
[2020-09-15 11:19:52 +0000] [46941] [INFO] Starting gunicorn 20.0.4
[2020-09-15 11:19:52 +0000] [46941] [INFO] Listening at: http://127.0.0.1:8000 (46941)
[2020-09-15 11:19:52 +0000] [46941] [INFO] Using worker: sync
[2020-09-15 11:19:52 +0000] [46943] [INFO] Booting worker with pid: 46943
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /favicon.ico
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /.well-known/security.txt
Not Found: /favicon.ico
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /favicon.ico
Not Found: /solr/admin/info/system
Not Found: /favicon.ico
Not Found: /shell
Not Found: /index.php
Not Found: /ReportServer
Not Found: /wp-login.php
Not Found: /wp-content/plugins/ioptimization/IOptimize.php
Not Found: /wp-content/plugins/ioptimization/IOptimize.php
Not Found: /wp-content/index.php
Not Found: /wp-content/plugins/ioptimization/IOptimize.php
Not Found: /wp-content/plugins/ioptimization/cehjuwesbz.php
Not Found: /wp-content/plugins/ioptimization/IOptimize.php
Not Found: /wp-content/plugins/ioptimization/cehjuwesbz.php
Not Found: /boaform/admin/formLogin
Not Found: /api/jsonws/invoke
Not Found: /setup.cgi
Not Found: /nkvm/postplain/
Not Found: /nkvm/postplain/
Not Found: /ncsi.txt
Not Found: /HNAP1/
Not Found: /hudson/script
Not Found: /script
Not Found: /sqlite/main.php
Not Found: /sqlitemanager/main.php
Not Found: /SQLiteManager/main.php
Not Found: /SQLite/main.php
Not Found: /SQlite/main.php
Not Found: /main.php
Not Found: /test/sqlite/SQLiteManager-1.2.0/SQLiteManager-1.2.0/main.php
Not Found: /SQLiteManager-1.2.4/main.php
Not Found: /agSearch/SQlite/main.php
[2020-09-15 19:11:10 +0000] [46941] [INFO] Handling signal: term
[2020-09-15 19:11:10 +0000] [46943] [INFO] Worker exiting (pid: 46943)
[2020-09-15 19:11:10 +0000] [46941] [INFO] Shutting down: Master
[2020-09-15 19:50:47 +0000] [50864] [INFO] Starting gunicorn 20.0.4
[2020-09-15 19:50:47 +0000] [50864] [INFO] Listening at: http://127.0.0.1:8000 (50864)
[2020-09-15 19:50:47 +0000] [50864] [INFO] Using worker: sync
[2020-09-15 19:50:47 +0000] [50866] [INFO] Booting worker with pid: 50866
Not Found: /solr/admin/info/system
Not Found: /index.php
Internal Server Error: /number_mac_mem/5
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/main/views.py", line 123, in mac_rub_mem
    mac_name=mac[0].mac_adr
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Internal Server Error: /number_mac_mem/5
Traceback (most recent call last):
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/main/views.py", line 123, in mac_rub_mem
    mac_name=mac[0].mac_adr
  File "/myproject/myprojectenv/lib/python3.8/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2020-09-15 20:18:31 +0000] [50864] [INFO] Handling signal: term
[2020-09-15 20:18:31 +0000] [50866] [INFO] Worker exiting (pid: 50866)
[2020-09-15 20:18:31 +0000] [50864] [INFO] Shutting down: Master
[2020-09-15 20:18:40 +0000] [51097] [INFO] Starting gunicorn 20.0.4
[2020-09-15 20:18:40 +0000] [51097] [INFO] Listening at: http://127.0.0.1:8000 (51097)
[2020-09-15 20:18:40 +0000] [51097] [INFO] Using worker: sync
[2020-09-15 20:18:40 +0000] [51099] [INFO] Booting worker with pid: 51099
