[2020-08-30 04:24:41 -0700] [5346] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:24:41 -0700] [5346] [INFO] Listening at: http://127.0.0.1:8000 (5346)
[2020-08-30 04:24:41 -0700] [5346] [INFO] Using worker: sync
[2020-08-30 04:24:41 -0700] [5350] [INFO] Booting worker with pid: 5350
[2020-08-30 04:26:05 -0700] [5346] [INFO] Handling signal: term
[2020-08-30 11:26:05 +0000] [5350] [INFO] Worker exiting (pid: 5350)
[2020-08-30 04:26:05 -0700] [5346] [INFO] Shutting down: Master
[2020-08-30 04:26:05 -0700] [5376] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:26:05 -0700] [5376] [INFO] Listening at: http://127.0.0.1:8000 (5376)
[2020-08-30 04:26:05 -0700] [5376] [INFO] Using worker: sync
[2020-08-30 04:26:05 -0700] [5379] [INFO] Booting worker with pid: 5379
Not Found: /ws/data/
[2020-08-30 04:29:13 -0700] [5376] [INFO] Handling signal: term
[2020-08-30 11:29:13 +0000] [5379] [INFO] Worker exiting (pid: 5379)
[2020-08-30 04:29:14 -0700] [5376] [INFO] Shutting down: Master
[2020-08-30 04:29:14 -0700] [5445] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:29:14 -0700] [5445] [INFO] Listening at: http://127.0.0.1:8000 (5445)
[2020-08-30 04:29:14 -0700] [5445] [INFO] Using worker: sync
[2020-08-30 04:29:14 -0700] [5448] [INFO] Booting worker with pid: 5448
Not Found: /ws/data/
[2020-08-30 04:30:54 -0700] [5445] [INFO] Handling signal: term
[2020-08-30 11:30:54 +0000] [5448] [INFO] Worker exiting (pid: 5448)
[2020-08-30 04:30:54 -0700] [5445] [INFO] Shutting down: Master
[2020-08-30 04:30:55 -0700] [5484] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:30:55 -0700] [5484] [INFO] Listening at: http://127.0.0.1:8000 (5484)
[2020-08-30 04:30:55 -0700] [5484] [INFO] Using worker: sync
[2020-08-30 04:30:55 -0700] [5487] [INFO] Booting worker with pid: 5487
Not Found: /ws/data/
[2020-08-30 04:32:51 -0700] [5484] [INFO] Handling signal: term
[2020-08-30 11:32:51 +0000] [5487] [INFO] Worker exiting (pid: 5487)
[2020-08-30 04:32:51 -0700] [5484] [INFO] Shutting down: Master
[2020-08-30 04:32:52 -0700] [5593] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:32:52 -0700] [5593] [INFO] Listening at: http://127.0.0.1:8000 (5593)
[2020-08-30 04:32:52 -0700] [5593] [INFO] Using worker: sync
[2020-08-30 04:32:52 -0700] [5596] [INFO] Booting worker with pid: 5596
Not Found: /ws/data/
[2020-08-30 04:33:27 -0700] [5593] [INFO] Handling signal: term
[2020-08-30 11:33:27 +0000] [5596] [INFO] Worker exiting (pid: 5596)
[2020-08-30 04:33:27 -0700] [5593] [INFO] Shutting down: Master
[2020-08-30 04:33:27 -0700] [5610] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:33:27 -0700] [5610] [INFO] Listening at: http://127.0.0.1:8000 (5610)
[2020-08-30 04:33:27 -0700] [5610] [INFO] Using worker: sync
[2020-08-30 04:33:27 -0700] [5613] [INFO] Booting worker with pid: 5613
Not Found: /ws/data/
Not Found: /ws/data/
Not Found: /ws/data/
Not Found: /favicon.ico
[2020-08-30 04:35:49 -0700] [5610] [INFO] Handling signal: term
[2020-08-30 11:35:49 +0000] [5613] [INFO] Worker exiting (pid: 5613)
[2020-08-30 04:35:49 -0700] [5610] [INFO] Shutting down: Master
[2020-08-30 04:35:50 -0700] [5678] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:35:50 -0700] [5678] [INFO] Listening at: http://127.0.0.1:8000 (5678)
[2020-08-30 04:35:50 -0700] [5678] [INFO] Using worker: sync
[2020-08-30 04:35:50 -0700] [5681] [INFO] Booting worker with pid: 5681
Not Found: /ws/data/
Not Found: /ws/data/
Not Found: /ws/data/
[2020-08-30 04:40:11 -0700] [5678] [INFO] Handling signal: term
[2020-08-30 11:40:11 +0000] [5681] [INFO] Worker exiting (pid: 5681)
[2020-08-30 04:40:11 -0700] [5678] [INFO] Shutting down: Master
[2020-08-30 04:40:11 -0700] [5817] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:40:11 -0700] [5817] [INFO] Listening at: http://127.0.0.2:8000 (5817)
[2020-08-30 04:40:11 -0700] [5817] [INFO] Using worker: sync
[2020-08-30 04:40:11 -0700] [5820] [INFO] Booting worker with pid: 5820
[2020-08-30 04:43:34 -0700] [5817] [INFO] Handling signal: term
[2020-08-30 11:43:34 +0000] [5820] [INFO] Worker exiting (pid: 5820)
[2020-08-30 04:43:34 -0700] [5817] [INFO] Shutting down: Master
[2020-08-30 04:43:34 -0700] [5973] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:43:34 -0700] [5973] [INFO] Listening at: http://127.0.0.2:8000 (5973)
[2020-08-30 04:43:34 -0700] [5973] [INFO] Using worker: sync
[2020-08-30 04:43:34 -0700] [5976] [INFO] Booting worker with pid: 5976
Not Found: /ws/data/
Not Found: /ws/data/
Not Found: /ws/data/
Not Found: /ws/data/
[2020-08-30 04:49:08 -0700] [5973] [INFO] Handling signal: term
[2020-08-30 11:49:08 +0000] [5976] [INFO] Worker exiting (pid: 5976)
[2020-08-30 04:49:08 -0700] [5973] [INFO] Shutting down: Master
[2020-08-30 04:49:08 -0700] [6238] [INFO] Starting gunicorn 20.0.4
[2020-08-30 04:49:08 -0700] [6238] [INFO] Listening at: http://127.0.0.2:8000 (6238)
[2020-08-30 04:49:08 -0700] [6238] [INFO] Using worker: sync
[2020-08-30 04:49:08 -0700] [6241] [INFO] Booting worker with pid: 6241
Not Found: /ws/data/
[2020-08-30 06:54:08 -0700] [1186] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:08 -0700] [1186] [INFO] Listening at: http://127.0.0.2:8000 (1186)
[2020-08-30 06:54:08 -0700] [1186] [INFO] Using worker: sync
[2020-08-30 06:54:08 -0700] [1209] [INFO] Booting worker with pid: 1209
[2020-08-30 13:54:30 +0000] [1209] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:31 +0000] [1209] [INFO] Worker exiting (pid: 1209)
[2020-08-30 06:54:31 -0700] [1186] [INFO] Shutting down: Master
[2020-08-30 06:54:31 -0700] [1186] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:32 -0700] [1297] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:32 -0700] [1297] [INFO] Listening at: http://127.0.0.2:8000 (1297)
[2020-08-30 06:54:32 -0700] [1297] [INFO] Using worker: sync
[2020-08-30 06:54:32 -0700] [1300] [INFO] Booting worker with pid: 1300
[2020-08-30 13:54:33 +0000] [1300] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:33 +0000] [1300] [INFO] Worker exiting (pid: 1300)
[2020-08-30 06:54:33 -0700] [1297] [INFO] Shutting down: Master
[2020-08-30 06:54:33 -0700] [1297] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:34 -0700] [1306] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:34 -0700] [1306] [INFO] Listening at: http://127.0.0.2:8000 (1306)
[2020-08-30 06:54:34 -0700] [1306] [INFO] Using worker: sync
[2020-08-30 06:54:34 -0700] [1309] [INFO] Booting worker with pid: 1309
[2020-08-30 13:54:35 +0000] [1309] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:35 +0000] [1309] [INFO] Worker exiting (pid: 1309)
[2020-08-30 06:54:35 -0700] [1306] [INFO] Shutting down: Master
[2020-08-30 06:54:35 -0700] [1306] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:36 -0700] [1371] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:36 -0700] [1371] [INFO] Listening at: http://127.0.0.2:8000 (1371)
[2020-08-30 06:54:36 -0700] [1371] [INFO] Using worker: sync
[2020-08-30 06:54:36 -0700] [1375] [INFO] Booting worker with pid: 1375
[2020-08-30 13:54:37 +0000] [1375] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:37 +0000] [1375] [INFO] Worker exiting (pid: 1375)
[2020-08-30 06:54:37 -0700] [1371] [INFO] Shutting down: Master
[2020-08-30 06:54:37 -0700] [1371] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:39 -0700] [1424] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:39 -0700] [1424] [INFO] Listening at: http://127.0.0.2:8000 (1424)
[2020-08-30 06:54:39 -0700] [1424] [INFO] Using worker: sync
[2020-08-30 06:54:39 -0700] [1427] [INFO] Booting worker with pid: 1427
[2020-08-30 13:54:40 +0000] [1427] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:40 +0000] [1427] [INFO] Worker exiting (pid: 1427)
[2020-08-30 06:54:40 -0700] [1424] [INFO] Shutting down: Master
[2020-08-30 06:54:40 -0700] [1424] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:41 -0700] [1438] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:41 -0700] [1438] [INFO] Listening at: http://127.0.0.2:8000 (1438)
[2020-08-30 06:54:41 -0700] [1438] [INFO] Using worker: sync
[2020-08-30 06:54:41 -0700] [1441] [INFO] Booting worker with pid: 1441
[2020-08-30 13:54:42 +0000] [1441] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:42 +0000] [1441] [INFO] Worker exiting (pid: 1441)
[2020-08-30 06:54:42 -0700] [1438] [INFO] Shutting down: Master
[2020-08-30 06:54:42 -0700] [1438] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:43 -0700] [1476] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:43 -0700] [1476] [INFO] Listening at: http://127.0.0.2:8000 (1476)
[2020-08-30 06:54:43 -0700] [1476] [INFO] Using worker: sync
[2020-08-30 06:54:43 -0700] [1479] [INFO] Booting worker with pid: 1479
[2020-08-30 13:54:44 +0000] [1479] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:44 +0000] [1479] [INFO] Worker exiting (pid: 1479)
[2020-08-30 06:54:44 -0700] [1476] [INFO] Shutting down: Master
[2020-08-30 06:54:44 -0700] [1476] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:45 -0700] [1481] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:45 -0700] [1481] [INFO] Listening at: http://127.0.0.2:8000 (1481)
[2020-08-30 06:54:45 -0700] [1481] [INFO] Using worker: sync
[2020-08-30 06:54:45 -0700] [1484] [INFO] Booting worker with pid: 1484
[2020-08-30 13:54:46 +0000] [1484] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:46 +0000] [1484] [INFO] Worker exiting (pid: 1484)
[2020-08-30 06:54:46 -0700] [1481] [INFO] Shutting down: Master
[2020-08-30 06:54:46 -0700] [1481] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:47 -0700] [1531] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:47 -0700] [1531] [INFO] Listening at: http://127.0.0.2:8000 (1531)
[2020-08-30 06:54:47 -0700] [1531] [INFO] Using worker: sync
[2020-08-30 06:54:47 -0700] [1534] [INFO] Booting worker with pid: 1534
[2020-08-30 13:54:48 +0000] [1534] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:48 +0000] [1534] [INFO] Worker exiting (pid: 1534)
[2020-08-30 06:54:48 -0700] [1531] [INFO] Shutting down: Master
[2020-08-30 06:54:48 -0700] [1531] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:49 -0700] [1595] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:49 -0700] [1595] [INFO] Listening at: http://127.0.0.2:8000 (1595)
[2020-08-30 06:54:49 -0700] [1595] [INFO] Using worker: sync
[2020-08-30 06:54:49 -0700] [1598] [INFO] Booting worker with pid: 1598
[2020-08-30 13:54:50 +0000] [1598] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:50 +0000] [1598] [INFO] Worker exiting (pid: 1598)
[2020-08-30 06:54:50 -0700] [1595] [INFO] Shutting down: Master
[2020-08-30 06:54:50 -0700] [1595] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:52 -0700] [1600] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:52 -0700] [1600] [INFO] Listening at: http://127.0.0.2:8000 (1600)
[2020-08-30 06:54:52 -0700] [1600] [INFO] Using worker: sync
[2020-08-30 06:54:52 -0700] [1603] [INFO] Booting worker with pid: 1603
[2020-08-30 13:54:53 +0000] [1603] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:53 +0000] [1603] [INFO] Worker exiting (pid: 1603)
[2020-08-30 06:54:53 -0700] [1600] [INFO] Shutting down: Master
[2020-08-30 06:54:53 -0700] [1600] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:54 -0700] [1606] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:54 -0700] [1606] [INFO] Listening at: http://127.0.0.2:8000 (1606)
[2020-08-30 06:54:54 -0700] [1606] [INFO] Using worker: sync
[2020-08-30 06:54:54 -0700] [1609] [INFO] Booting worker with pid: 1609
[2020-08-30 13:54:55 +0000] [1609] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:55 +0000] [1609] [INFO] Worker exiting (pid: 1609)
[2020-08-30 06:54:55 -0700] [1606] [INFO] Shutting down: Master
[2020-08-30 06:54:55 -0700] [1606] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:56 -0700] [1612] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:56 -0700] [1612] [INFO] Listening at: http://127.0.0.2:8000 (1612)
[2020-08-30 06:54:56 -0700] [1612] [INFO] Using worker: sync
[2020-08-30 06:54:56 -0700] [1615] [INFO] Booting worker with pid: 1615
[2020-08-30 13:54:56 +0000] [1615] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mvlab/myprojectdir/myproject/asgi.py", line 16, in <module>
    application = get_asgi_application()
NameError: name 'get_asgi_application' is not defined
[2020-08-30 13:54:56 +0000] [1615] [INFO] Worker exiting (pid: 1615)
[2020-08-30 06:54:57 -0700] [1612] [INFO] Shutting down: Master
[2020-08-30 06:54:57 -0700] [1612] [INFO] Reason: Worker failed to boot.
[2020-08-30 06:54:59 -0700] [1617] [INFO] Starting gunicorn 20.0.4
[2020-08-30 06:54:59 -0700] [1617] [INFO] Listening at: http://127.0.0.2:8000 (1617)
[2020-08-30 06:54:59 -0700] [1617] [INFO] Using worker: sync
[2020-08-30 06:54:59 -0700] [1620] [INFO] Booting worker with pid: 1620
[2020-08-30 13:54:59 +0000] [1620] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/mvlab/myprojectdir/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
tt
